version: '3'

services:
  keycloak1:
    image: quay.io/keycloak/keycloak
    ports:
      - "8088:8088"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    
    network_mode: "host"
    volumes:
      - ./keycloak-data:/opt/keycloak/data/h2/
    command: 
      - start-dev 
      - --http-port=8088
      - -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
